services:
  db:
    image: postgres:17.6
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    container_name: cakeshop-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
volumes:
  postgres-data:





