spring.application.name=cakeshop
# Setting profile
spring.profiles.active=dev

#JWT config
#1 hour
jwt.expiration=3600000

# Max file size config
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=12MB

# Reset password time
password.reset-token-time=15

