# Database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Configuracion jwt
jwt.secret=${JWT_SECRET}
#1 hour
jwt.expiration=3600000

#Cloudinary config
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#Max file size config
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=12MB

#Resend config
resend.api-key=${RESEND_APY_KEY}
resend.from-email=${RESEND_FROM_EMAIL}


#Reset password time
password.reset-token-time=15

# application.properties
# spring.jpa.open-in-view=false

# Front config
frontend.url=${FRONT_URL}